#include<iostream>
#include "List.h"
using namespace std;
int main() {
	List list;
	list.InsertAtEnd(1);
	list.InsertAtStart(2);
	list.InsertAtStart(3);
	list.InsertAtStart(4);
	list.InsertAtStart(5);
	list.InsertAtEnd(6);
	list.InsertAtEnd(7);
	list.InsertAtEnd(8);
	list.ShowList();
	list.InsertAfterNode(list.SearchNode(5), 10);
	list.InsertAfterNode(list.SearchNode(100), 11);
	list.InsertAfterNode(list.SearchNode(8), 11);
	list.ShowList();
	list.DeleteAfterNode(list.SearchNode(5));
	list.ShowList();
	list.DeleteAfterNode(list.SearchNode(6));
	list.ShowList();
	list.DeleteAfterNode(list.SearchNode(11));
	list.ShowList();
	list.DeleteNode(5);
	list.ShowList();
	list.DeleteNode(8);
	list.ShowList();
	list.DeleteNode(11);
	list.ShowList();
	List ordereredList;
	ordereredList.InsertSorted(5);
	ordereredList.InsertSorted(4);
	ordereredList.InsertSorted(10);
	ordereredList.InsertSorted(12);
	ordereredList.InsertSorted(17);
	ordereredList.InsertSorted(1);
	ordereredList.ShowList();
	ordereredList.InsertSorted(5);
	ordereredList.DeleteNode(1);
	ordereredList.ShowList(); 
	ordereredList.InsertSorted(3);
	ordereredList.ShowList();
	cout << "\nUsing revrese function\n\n";
	ordereredList.Reverse();
	ordereredList.ShowList();
	ordereredList.InsertAtEnd(1);
	ordereredList.ShowList();
	List one;
	one.Reverse();
	one.InsertSorted(5);
	one.ShowList();
	one.Reverse();
	one.InsertSorted(10);
	one.ShowList();
	one.Reverse();
	one.ShowList();
	return 0;
}